// angular/routing/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingService} from '../services/shoppingservice.service';
import {ShoppingItem} from '../models/shoppingitem.model';
@Component({
	selector:"shopping-form",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	item:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingservice:ShoppingService) {}
	
	addToList() {
		this._shoppingservice.addToList(this.item);
		this.item = new ShoppingItem("",0,0,0);
	}
}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
		<label for="type">Item type:</label>
		<input type="text"
				name="type"
				[(ngModel)]="item.type"/>
	</div>
	<div class="form-group">
		<label for="count">Count:</label>
		<input type="number"
				name="count"
				minimum="0"
				[(ngModel)]="item.count"/>
	</div>
	<div class="form-group">
		<label for="price">Price:</label>
		<input type="number"
				name="price"
				step="0.01" minimum="0"
				[(ngModel)]="item.price"/>
	</div>
	<button class="btn btn-secondary" type="submit">Add</button>
</form>

// react/example_app/1_stage/frontend/src/components/ShoppingForm.js
import React from 'react'
import {Form,Button} from 'semantic-ui-react';

export default class ShoppingForm extends React.Component {

	constructor(props) {
		super(props);
		this.state = {
			type:"",
			price:0,
			count:0,
			id:0
		}
	}
	
	onChange = (event) => {
		let state = {};
		state[event.target.name] = event.target.value
		this.setState(state);
	}
	
	onSubmit = (event) => {
		event.preventDefault();
		let item = {
			type:this.state.type,
			count:this.state.count,
			price:this.state.price,
			id:0
		}
		this.props.addToList(item);
		this.setState({
			id:0,
			type:"",
			count:0,
			price:0
		})
	}
	
	render() {
		return(<Form onSubmit={this.onSubmit}>
				<Form.Field>
					<label htmlFor="type">Type:</label>
					<input type="text"
						   name="type"
						   onChange={this.onChange}
						   value={this.state.type}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="count">Count:</label>
					<input type="number"
							minimum="0"
						   name="count"
						   onChange={this.onChange}
						   value={this.state.count}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="price">Price:</label>
					<input type="number"
						   name="price"
						   minimum="0"
							step="0.01"
						   onChange={this.onChange}
						   value={this.state.price}/>
				</Form.Field>
				<Button type="submit">Add</Button>
				</Form>
				)
	}
}
